[auth]
redirect_uri = "http://localhost:8501/oauth2callback"  # Altere para URL de produção quando necessário
cookie_secret = "sua_chave_secreta_gerada_aleatoriamente"  # Use: openssl rand -hex 32

# Configuração para Google (exemplo)
[auth.google]
client_id = "seu_client_id_do_google"
client_secret = "seu_client_secret_do_google"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

# Configuração para Microsoft (opcional)
[auth.microsoft]
client_id = "seu_client_id_da_microsoft"
client_secret = "seu_client_secret_da_microsoft"
server_metadata_url = "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration"
